#### Experiments ####

ConfOptions:
  Bits: 16
  NetworkSize: 10000
  BinSize: 16
  RangeAddress: 65536
  Originators: 1000
  RefreshRate: 8
  Threshold: 16
  RandomSeed: 123456789
  MaxProximityOrder: 16
  Price: 1
  Chunks: 10000
  RequestsPerSecond: 12500
  EdgeLock: true
  SameOriginator: false
  PrecomputeRespNodes: true
  WriteRoutesToFile: false
  WriteStatesToFile: false
  IterationMeansUniqueChunk: false
  DebugPrints: false
  DebugInterval: 1000000
  NumRoutingGoroutines: 25
  Epoch: 1
  Iterations: 1_000_000

# omega: maxPoCheckEnabled
# k20p20: bucket size 20 and 20% originators
# k20p100: bucket size 20 and 100% originators
# k16p20: bucket size 16 and 20% originators
# k16p100: bucket size 16 and 100% originators
# k8p20: bucket size 8 and 20% originators
# k8p100: bucket size 8 and 100% originators
# k4p20: bucket size 4 and 20% originators
# k4p100: bucket size 4 and 100% originators
#
# empty or default for default
# custom for custom

Experiment:
  ExperimentName: "k20p100"

Custom:
  ThresholdEnabled:                 true # The maximum limit of debt an edge can have in one direction
  ForgivenessEnabled:               true # Edge debt gets forgiven some amount on an interval (amortized)
  ForgivenessDuringRouting:         true # If the forgiveness should happen before threshold is checked or after in updateGraph
  PaymentEnabled:                   false # Nodes pay if they Threshold fail
  MaxPOCheckEnabled:                false # Used to find the proper variable called "omega" in the python paper
  OnlyOriginatorPays:               false # Only the originator will pay, others will threshold fail or wait
  PayOnlyForCurrentRequest:         false # Only pay for current request or the full debt on the edge
  PayIfOrigPays:                    false # Only pay if the originator pays -- NOT NEEDED
  ForwarderPayForceOriginatorToPay: false # If Threshold fails, forces all the nodes in the route to pay for the current request
  WaitingEnabled:                   true # When Threshold fails, will wait before trying to traverse same route
  RetryWithAnotherPeer:             true # The Route to the chunk will try to take many paths to find the chunk
  CacheIsEnabled:                   false # Cache, which stores previously looked after chunks on the nodes
  PreferredChunks:                  false # Fits well with cache, where some chunkIds are chosen more often
  AdjustableThreshold:              false # The Threshold limit of an edge is determined based on the XOR distance

