name: TestUtils

on:
  push:
    branches:
      - master 

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - users: actions/checkout@v2

    - name: TestUtils
        run: go test -v ./...
